# Generated by Django 2.2 on 2021-03-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='group name')),
                ('slug', models.SlugField(max_length=100)),
                ('discription', models.TextField(blank=True, db_index=True)),
            ],
        ),
    ]
